/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardSecurityRouteImport } from './routes/_dashboard/security'
import { Route as DashboardOrganizationRouteImport } from './routes/_dashboard/organization'
import { Route as DashboardMembersRouteImport } from './routes/_dashboard/members'
import { Route as DashboardInfrastructureRouteImport } from './routes/_dashboard/infrastructure'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/_dashboard/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/_dashboard/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationRoute = DashboardOrganizationRouteImport.update({
  id: '/_dashboard/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/_dashboard/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInfrastructureRoute = DashboardInfrastructureRouteImport.update({
  id: '/_dashboard/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/infrastructure': typeof DashboardInfrastructureRoute
  '/members': typeof DashboardMembersRoute
  '/organization': typeof DashboardOrganizationRoute
  '/security': typeof DashboardSecurityRoute
  '/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infrastructure': typeof DashboardInfrastructureRoute
  '/members': typeof DashboardMembersRoute
  '/organization': typeof DashboardOrganizationRoute
  '/security': typeof DashboardSecurityRoute
  '/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/infrastructure': typeof DashboardInfrastructureRoute
  '/_dashboard/members': typeof DashboardMembersRoute
  '/_dashboard/organization': typeof DashboardOrganizationRoute
  '/_dashboard/security': typeof DashboardSecurityRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/infrastructure'
    | '/members'
    | '/organization'
    | '/security'
    | '/settings'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/infrastructure'
    | '/members'
    | '/organization'
    | '/security'
    | '/settings'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_dashboard/infrastructure'
    | '/_dashboard/members'
    | '/_dashboard/organization'
    | '/_dashboard/security'
    | '/_dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DashboardInfrastructureRoute: typeof DashboardInfrastructureRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardOrganizationRoute: typeof DashboardOrganizationRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/security': {
      id: '/_dashboard/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/organization': {
      id: '/_dashboard/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof DashboardOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/members': {
      id: '/_dashboard/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/infrastructure': {
      id: '/_dashboard/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof DashboardInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DashboardInfrastructureRoute: DashboardInfrastructureRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardOrganizationRoute: DashboardOrganizationRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
